### ISSUE TITLE
Scale tables so that it fits in the view window

### ISSUE THREAD

**Issue by ahnj12** [luisnaranjo733/info474-final#10]
Make it so that the tables adjust based on view width and height

**Comment by luisnaranjo733** [comment]
is this still an issue that needs to be fixed?
It looks fine on my machine, so I can't really reproduce.

**Comment by ahnj12** [comment]
I think we may just leave it as is. I started to look into it and I realized there would be a lot of refactoring needed due to all the hard coded pixels we have. I figured it wasn't worth it because it will look fine on monitors greater than 13".
