### ISSUE TITLE
Do we want to add a automatic play feature?

### ISSUE THREAD

**Issue by luisnaranjo733** [luisnaranjo733/info474-final#6]
Freeman suggested a play feature in his comment on our project proposal.

Is this something we want to tackle?

> Sounds like an interesting project. There are two goals that your prompt describes: - Explain *how* the algorithm works - Compare the algorithm to other approaches While your wireframe provides a venue for showcasing an implementation of the algorithm (an important piece of this process), I think there need to be additions in order to answer the prompts above. For example, showing a walk-through of how (at each step) a decision is made (checking availability / assessing table size v.s. group size / etc.) is important. A potential user of the software should be able to understand how this algorithm differs from other approaches, both in general and in specific contexts (does it seat 2 people at a 4 person table if the 2nd group in line is 4 people?). One way to help do this would be to expose the parameters of your model via controls (i.e., allow the user to set the mean/standard-deviation of the busyness, adjust the number of seats, set the flow-rate of incoming persons, etc.). It would also be helpful to have a side by side comparison of algorithms (see: sorting.at) to understand how much better this performs. While a stepper can help understand individual steps, it also would be helpful to have the simulation run automatically over a period of time to show the fluctuations in wait-time / line length / meal-time / etc. Looking forward to seeing this project get developed!
> Michael Freeman, May 19 at 1:30pm

**Comment by ahnj12** [comment]
this is done
